"""add color column to tag model

Revision ID: f69369755296
Revises: b1ff121d00db
Create Date: 2025-10-23 06:37:19.847599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f69369755296"
down_revision = "b1ff121d00db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # colorカラムをNOT NULLで直接追加（デフォルト値付き）
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "color", sa.String(length=7), nullable=False, server_default="#667eea"
            )
        )

    # デフォルト値を削除（以降は明示的に指定する必要がある）
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.alter_column("color", server_default=None)

    # unique制約の追加
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["name"])

    # todoテーブルの型変更
    with op.batch_alter_table("todo", schema=None) as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=sa.VARCHAR(length=256),
            type_=sa.String(length=1024),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.TIMESTAMP(),
            type_=sa.DateTime(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # todoテーブルの型を戻す
    with op.batch_alter_table("todo", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.TIMESTAMP(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "content",
            existing_type=sa.String(length=1024),
            type_=sa.VARCHAR(length=256),
            existing_nullable=False,
        )

    # unique制約を削除
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # colorカラムを削除
    with op.batch_alter_table("tag", schema=None) as batch_op:
        batch_op.drop_column("color")
    # ### end Alembic commands ###
